version: '3.8'
services:
  task-manager:
    container_name: task-manager-container
    image: task-manager-img
    build: .
    ports:
      - 9090:9090
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - redis
      - mysql
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - task-manager-vol:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  redis:
    image: redis
volumes:
  task-manager-vol:
